/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import java.util.Scanner;

import javax.swing.SwingUtilities;

import arenas.ArenaCombate;
import excecoes.CreatureCannotAttackException;
import excecoes.EmptyDeckException;
import excecoes.ManaInsuficienteException;

/**
 *
 * @author adene
 */
public class NomearJogadoresTela extends javax.swing.JFrame {

    private NomearJogadores nomearJogadoresl;
    private MontadorDeck deck;
    private FimDaBatalha batalhaFim;
    private ArenaCombate arena;
    
    
    public NomearJogadoresTela() {
    	this.nomearJogadoresl = new NomearJogadores();
    	this.deck = new MontadorDeck();
    	this.batalhaFim = new FimDaBatalha();
    	this.arena = new ArenaCombate();
    	initComponents();
    }

 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJogador1 = new javax.swing.JLabel();
        nomeJogador1 = new javax.swing.JTextField();
        lblJogador2 = new javax.swing.JLabel();
        nomeJogador2 = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJogador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJogador1.setForeground(new java.awt.Color(255, 51, 51));
        lblJogador1.setText("Jogador 1:");

        nomeJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeJogador1ActionPerformed(evt);
            }
        });

        lblJogador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJogador2.setForeground(new java.awt.Color(255, 51, 51));
        lblJogador2.setText("Jogador 2:");

        nomeJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeJogador2ActionPerformed(evt);
            }
        });

        btnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 51, 51));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeJogador1)
                    .addComponent(lblJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeJogador2)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(lblJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(nomeJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(nomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeJogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeJogador2ActionPerformed

    private void nomeJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeJogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeJogador1ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        nomearJogadoresl.getJogadores().get(0).setNome(nomeJogador1.getText());
        nomearJogadoresl.getJogadores().get(1).setNome(nomeJogador2.getText());
        
        // Passando os jogadores nomeados para a próxima tela
        MontadorDeckTela montador = new MontadorDeckTela(nomearJogadoresl.getJogadores());
        montador.setVisible(true);
    }


    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) {
            SwingUtilities.invokeLater(() -> {
            NomearJogadoresTela tela = new NomearJogadoresTela();
            tela.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JTextField nomeJogador1;
    private javax.swing.JTextField nomeJogador2;
    // End of variables declaration//GEN-END:variables
}
